### ISSUE TITLE
API Data

### ISSUE THREAD

**Issue by g7shah** [the-game-code/covid19#1]
Hello,

Apparently, the data shown for France Total cases does not match with the data displayed on https://www.worldometers.info/coronavirus/
The difference is about 20k.

**Comment by rishabh115** [comment]
@g7shah He is using a different API for fetching the data that's why the data is inconsistent . Try using this library, [CovidMapper](https://github.com/rishabh115/CovidMapper). It directly processes the data from **worldometers** and provides you the result in the form of a list directly.
